/**
 * The Contact modal's search (Tom, 4 Oct 2026: "a search bar at the top of
 * the page when adding a new contact for an estimate").
 *
 * The search runs on the SERVER. The first cut filtered a list the builder
 * loaded at page time — and the moment every CRM customer was mirrored into
 * Contacts (20270210) that list passed PostgREST's 1,000-row cap, so anyone
 * past the first thousand surnames could not be found at all. One rule here
 * builds the PostgREST `or()` filter; the Contacts page's `?q=` and the
 * modal's box both ask the table the same question.
 *
 * Matches a case-insensitive substring of first name, last name, company,
 * email or suburb; a phone matches digits against the stored digits, so
 * "0412 345" and "0412345" both find a mobile saved as 0412 345 678.
 */

/** The cleaned needle: lower-cased, capped, with the characters that would
 * break an `or()` list or act as wildcards removed. Null when nothing is left. */
export function contactSearchNeedle(q: string): string | null {
  const needle = q.trim().slice(0, 80).toLowerCase().replace(/[%_,()]/g, "").trim();
  return needle || null;
}

/** The `or()` filter string for `supabase.from("contacts").or(...)`, or null for an empty query. */
export function contactSearchOr(q: string): string | null {
  const needle = contactSearchNeedle(q);
  if (!needle) return null;
  const like = `%${needle}%`;
  const parts = [
    `first_name.ilike.${like}`, `last_name.ilike.${like}`, `company.ilike.${like}`,
    `email.ilike.${like}`, `city.ilike.${like}`,
  ];
  // A phone is matched on its stored digits (`phone_digits`, generated by
  // 20270210) against the typed digits, so neither side's spacing matters.
  const digits = needle.replace(/[^0-9+]/g, "");
  if (digits.length >= 3) parts.push(`phone_digits.ilike.%${digits}%`, `landline_digits.ilike.%${digits}%`);
  return parts.join(",");
}
