import pg from "pg";
import { loadTestEnv, refuseProduction } from "./env.mjs";
loadTestEnv();
const url = process.env.E2E_DATABASE_URL || process.env.C1_DATABASE_URL || "";
refuseProduction(url);
const c = new pg.Client({ connectionString: url, ssl: { rejectUnauthorized: false } });
await c.connect();
const q = async (l, s) => console.log(l, (await c.query(s)).rows);
await q("open handoffs", `select (h.requested_at < now()-interval '3 days') old, (ac.account_id is null) no_account, count(*)::int from agent_handoffs h left join agent_conversations ac on ac.id=h.conversation_id where h.status in ('requested','claimed','active') group by 1,2 order by 3 desc`);
await q("conversation columns", `select column_name from information_schema.columns where table_name='agent_conversations' order by ordinal_position`);
await q("callbacks 90d", `select (occurred_at < now()-interval '3 days') old, (account_id is null) no_account, count(*)::int from crm_events where type='callback_requested' and occurred_at > now()-interval '90 days' group by 1,2`);
await q("confirmation_requests open", `select (created_at < now()-interval '3 days') old, count(*)::int from confirmation_requests where status not in ('done','closed','declined','cancelled') group by 1`);
await q("wizard buckets 30d", `select (last_seen_at < now()-interval '3 days') old, count(*)::int from wizard_drafts where bucket in ('ready_call','ready_visit','needs_help','priced_no_request') and last_seen_at > now()-interval '30 days' group by 1`);
await c.end();
