import pg from "pg";
import { loadTestEnv, refuseProduction } from "./env.mjs";
loadTestEnv();
const url = process.env.E2E_DATABASE_URL || process.env.C1_DATABASE_URL || "";
refuseProduction(url);
const c = new pg.Client({ connectionString: url, ssl: { rejectUnauthorized: false } });
await c.connect();
const q = async (l, s) => console.log(l, (await c.query(s)).rows);
await q("old bucket drafts by user presence", `select (d.user_id is null) no_user, (u.id is null) user_gone, (d.email ilike '%@example.com') ex, count(*)::int from wizard_drafts d left join auth.users u on u.id = d.user_id where d.bucket in ('ready_call','ready_visit','needs_help','priced_no_request') and d.last_seen_at > now()-interval '30 days' and d.last_seen_at < now()-interval '3 days' group by 1,2,3 order by 4 desc`);
await q("old bucket drafts: user created_at", `select to_char(min(u.created_at),'MM-DD') oldest_user, to_char(max(u.created_at),'MM-DD') newest_user, count(*)::int from wizard_drafts d join auth.users u on u.id = d.user_id where d.bucket in ('ready_call','ready_visit','needs_help','priced_no_request') and d.last_seen_at > now()-interval '30 days' and d.last_seen_at < now()-interval '3 days'`);
await c.end();
