import { chromium } from "playwright-core";
const BASE = "https://paint-group-platform.vercel.app";
const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto(`${BASE}/login`);
await page.fill('input[type="email"]', process.env.E2E_STAFF_EMAIL!);
await page.fill('input[type="password"]', process.env.E2E_STAFF_PASSWORD!);
await page.getByRole("button", { name: "Sign in", exact: true }).click();
await page.waitForURL(/estimates|dashboard|pc/, { timeout: 30000 }).catch(() => {});
const res = await page.request.get(`${BASE}/api/debug/pdf`, { timeout: 90000 });
console.log("status:", res.status());
console.log((await res.text()).slice(0, 800));
await browser.close();
