-- =============================================================================
-- Session 8 · Residential and commercial audiences (docs/briefs/website-audiences.md)
--
-- 1 · site_content — every string on both homepages, by audience, section
--     and key (§3). Public select (the marketing pages read with the anon
--     client, like showcase_jobs); NO client write policy — the only writer
--     is the zod'd server action through the service client. Seeded here
--     for BOTH audiences from lib/marketing/copy (generated by
--     scripts/gen-site-content-seed.ts), idempotent.
-- 2 · showcase_jobs.featured_rank_business — the business site's three
--     cards, a rank per audience (⚑ D4).
-- 3 · review_tags — Google reviews tagged home | business (§5). Keyed on
--     publish time + author (Google hands back no id). The import writes
--     audience_suggested; only the confirmed `audience` drives the filter.
-- A3 tenancy on both new tables. Idempotent; read-backs at the end.
-- =============================================================================

create table if not exists public.site_content (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references public.tenants (id) default public.current_tenant(),
  audience    text not null constraint site_content_audience_check check (audience in ('home', 'business')),
  section     text not null constraint site_content_section_shape check (section ~ '^[a-z_]{2,40}$'),
  key         text not null constraint site_content_key_shape check (key ~ '^[a-z0-9_]{1,60}$'),
  value       text not null default '' constraint site_content_value_len check (length(value) <= 20000),
  sort        integer not null default 0,
  updated_by  uuid references auth.users (id) on delete set null,
  updated_at  timestamptz not null default now(),
  constraint site_content_unique unique (tenant_id, audience, section, key, sort)
);
comment on table public.site_content is 'Session 8 §3: homepage copy per audience. Written only by app/(app)/settings/siteContentActions.ts (service client). Read by lib/marketing/siteCopy.ts with the anon client.';

create index if not exists site_content_audience_idx on public.site_content (tenant_id, audience, section);
create index if not exists site_content_updated_by_idx on public.site_content (updated_by) where updated_by is not null;

drop trigger if exists t_site_content_updated on public.site_content;
create trigger t_site_content_updated before update on public.site_content
  for each row execute function public.set_updated_at();

alter table public.site_content enable row level security;
drop policy if exists site_content_public_read on public.site_content;
create policy site_content_public_read on public.site_content for select to anon, authenticated using (true);
revoke insert, update, delete, truncate, references, trigger on public.site_content from anon, authenticated;
grant select on public.site_content to anon, authenticated;

-- ---- 2 · a rank per audience on showcase_jobs ------------------------------
alter table public.showcase_jobs add column if not exists featured_rank_business integer
  constraint showcase_jobs_rank_business_range check (featured_rank_business is null or featured_rank_business between 1 and 3);
create unique index if not exists showcase_jobs_featured_business_key on public.showcase_jobs (tenant_id, featured_rank_business) where featured_rank_business is not null;

-- ---- 3 · review tags ----------------------------------------------------------
create table if not exists public.review_tags (
  review_key         text primary key constraint review_tags_key_len check (length(review_key) between 3 and 200),
  tenant_id          uuid not null references public.tenants (id) default public.current_tenant(),
  author             text not null default '' constraint review_tags_author_len check (length(author) <= 120),
  published_at       timestamptz,
  rating             integer constraint review_tags_rating_range check (rating is null or rating between 1 and 5),
  snippet            text not null default '' constraint review_tags_snippet_len check (length(snippet) <= 400),
  audience_suggested text constraint review_tags_suggested_check check (audience_suggested is null or audience_suggested in ('home', 'business')),
  audience           text constraint review_tags_audience_check check (audience is null or audience in ('home', 'business')),
  seen_at            timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
comment on table public.review_tags is 'Session 8 §5: Google reviews tagged by audience. audience_suggested = the import''s guess; audience = confirmed in Settings → Website → Reviews. Only the confirmed tag filters.';
create index if not exists review_tags_audience_idx on public.review_tags (tenant_id, audience);

drop trigger if exists t_review_tags_updated on public.review_tags;
create trigger t_review_tags_updated before update on public.review_tags
  for each row execute function public.set_updated_at();

alter table public.review_tags enable row level security;
drop policy if exists review_tags_public_read on public.review_tags;
create policy review_tags_public_read on public.review_tags for select to anon, authenticated using (true);
revoke insert, update, delete, truncate, references, trigger on public.review_tags from anon, authenticated;
grant select on public.review_tags to anon, authenticated;

-- ---- seed (generated; idempotent) -------------------------------------------
insert into public.site_content (audience, section, key, value) values
  ('home', 'nav', 'link_1_label', 'Real jobs, real prices'),
  ('home', 'nav', 'link_1_href', '/work'),
  ('home', 'nav', 'link_2_label', 'How it works'),
  ('home', 'nav', 'link_2_href', '#how'),
  ('home', 'nav', 'link_3_label', 'For business'),
  ('home', 'nav', 'link_3_href', '#trade'),
  ('home', 'nav', 'link_4_label', 'Reviews'),
  ('home', 'nav', 'link_4_href', '#reviews'),
  ('home', 'nav', 'other_audience_label', 'For business →'),
  ('home', 'nav', 'cta', 'See my price'),
  ('home', 'hero', 'kicker', 'Melbourne · homes and businesses · see your price today · confirmed by a person before we start'),
  ('home', 'hero', 'h1', 'Transforming spaces.
Redefining painting.'),
  ('home', 'hero', 'lead', 'Type the address. A home, a shop, an office or a whole portfolio. See a real price range in about ten minutes.'),
  ('home', 'hero', 'talk_line', 'Rather talk to a person?'),
  ('home', 'hero', 'chip_home', 'My home'),
  ('home', 'hero', 'chip_business', 'A business or property I manage'),
  ('home', 'hero', 'chips_label', 'This is'),
  ('home', 'hero', 'placeholder', 'Type your address'),
  ('home', 'hero', 'button', 'See my price →'),
  ('home', 'estimator_examples', 'example_1_address', '12 Elm Street, Malvern'),
  ('home', 'estimator_examples', 'example_1_price', '$8,400 – $9,600'),
  ('home', 'estimator_examples', 'example_1_time', '9 min to a range'),
  ('home', 'estimator_examples', 'example_2_address', '9 Clarke Street, Beaumaris'),
  ('home', 'estimator_examples', 'example_2_price', '$14,200 – $15,800'),
  ('home', 'estimator_examples', 'example_2_time', '11 min · exterior'),
  ('home', 'estimator_examples', 'example_3_address', '27 Wattle Avenue, Coburg'),
  ('home', 'estimator_examples', 'example_3_price', '$5,300 – $6,100'),
  ('home', 'estimator_examples', 'example_3_time', '8 min · 3 rooms'),
  ('home', 'how_it_works', 'h2', 'Four steps. You’re in charge of every one.'),
  ('home', 'how_it_works', 'step_1_title', 'See your price'),
  ('home', 'how_it_works', 'step_1_body', 'Type your address, answer a few questions, add photos if you have them. A price range appears on screen. About ten minutes.'),
  ('home', 'how_it_works', 'step_2_title', 'We confirm it with you'),
  ('home', 'how_it_works', 'step_2_body', 'The more you tell us, the tighter the range. Our estimator will go through all of the details with you in person, or over the phone to confirm your price.'),
  ('home', 'how_it_works', 'step_3_title', 'Pick your dates'),
  ('home', 'how_it_works', 'step_3_body', 'Once the price is signed off, choose a start that suits you. We confirm your painter before we lock it in. You’ll know who’s coming.'),
  ('home', 'how_it_works', 'step_4_title', 'Sign off, then pay'),
  ('home', 'how_it_works', 'step_4_body', 'Photo updates in your portal. A walkthrough with you at the end. You sign off, then the final invoice is due.'),
  ('home', 'how_it_works', 'talk_line', 'Rather talk to a person first?'),
  ('home', 'jobs', 'kicker', 'Real jobs · real prices · inc. GST'),
  ('home', 'jobs', 'h2', 'What Melbourne properties actually cost to paint.'),
  ('home', 'jobs', 'lead', 'Every card is a finished job with the real price. Tap one and we’ll open the estimator pre-filled with the same scope.'),
  ('home', 'jobs', 'all_link', 'All jobs →'),
  ('home', 'promise', 'kicker', 'Our promise · in writing, in your portal'),
  ('home', 'promise', 'h2', 'Four things we put in writing before we start.'),
  ('home', 'promise', 'lead', 'Tap each one to see exactly what it looks like inside your job.'),
  ('home', 'promise', 'panel_kicker', 'What this looks like in your job'),
  ('home', 'promise', 'row_1_title', 'No surprises on the invoice'),
  ('home', 'promise', 'row_1_sub', 'Extra work is priced and approved by you before it starts.'),
  ('home', 'promise', 'row_1_heading', 'Your painter finds rotten timber behind the fascia. Here''s what happens next.'),
  ('home', 'promise', 'row_1_note', 'Declined variations are recorded on your completion report. Nothing lands on the invoice that you didn''t tap Approve on.'),
  ('home', 'promise', 'row_2_title', 'A price a person signs off with you'),
  ('home', 'promise', 'row_2_sub', 'Your range tightens as you go, then we confirm it together before anything is booked.'),
  ('home', 'promise', 'row_2_heading', 'Your range gets tighter with every answer. Then we sign it off together.'),
  ('home', 'promise', 'row_2_note', 'Every price is signed off by one of our people before it''s booked: a call for apartments, units and smaller jobs, a visit for larger or older homes. What we sign off together is what goes on the invoice.'),
  ('home', 'promise', 'row_3_title', 'You sign off before you pay'),
  ('home', 'promise', 'row_3_sub', 'The final invoice waits for your walkthrough.'),
  ('home', 'promise', 'row_3_heading', 'The last day on site is a walkthrough with you, area by area.'),
  ('home', 'promise', 'row_3_note', 'The walkthrough is done with you, on site. Flagged items are fixed first; the invoice follows your signature.'),
  ('home', 'promise', 'row_4_title', '2-year warranty, $20M insured'),
  ('home', 'promise', 'row_4_sub', 'Both documents sit in your portal from day one.'),
  ('home', 'promise', 'row_4_heading', 'Both documents are in your portal the day you accept.'),
  ('home', 'promise', 'row_4_note', 'Six months from now you''ll want to know which white is on the hallway. It''s here.'),
  ('home', 'story', 'kicker', 'Your portal · one job, start to finish · demo data'),
  ('home', 'story', 'h2', 'Watch it happen from wherever you are.'),
  ('home', 'story', 'lead', 'This is what five days looks like from your phone.'),
  ('home', 'story', 'phone_address', '12 Elm Street, Northcote'),
  ('home', 'story', 'phone_meta', 'Interior · 4 rooms + hallway · $9,180 inc. GST'),
  ('home', 'story', 'signed_line', 'Signed off · 12 Elm Street'),
  ('home', 'story', 'beat_1', 'Monday, 7:31am. Felipe''s on site.'),
  ('home', 'story', 'beat_2', 'You get a message before the first brush touches a wall.'),
  ('home', 'story', 'beat_3', 'Photos from the site.'),
  ('home', 'story', 'beat_4', 'Every area ticked off as it''s finished. No guessing.'),
  ('home', 'story', 'beat_5', 'An update in plain words at the end of each day.'),
  ('home', 'story', 'beat_6', 'Anything extra is priced and approved by you before it starts.'),
  ('home', 'story', 'beat_7', 'Then you walk it with us, room by room.'),
  ('home', 'story', 'beat_8', 'You sign off. Then you pay.'),
  ('home', 'live', 'heading', 'Live from the Paint Group platform'),
  ('home', 'painters', 'h2', 'Who’ll be painting.'),
  ('home', 'painters', 'lead', 'Our trusted network of painters. Every one is quality-checked, fully insured, and the kind of person you’ll be comfortable having in your home or on your premises. You’ll know who’s coming before the date is locked in.'),
  ('home', 'painters', 'rule_1', 'Your expectations are documented for your painter before day one. No nasty surprises, for you or for them.'),
  ('home', 'painters', 'rule_2', 'The finish you’re paying for is written on the work order, room by room.'),
  ('home', 'painters', 'rule_3', 'Photos from the site, so you never have to wonder how it’s going.'),
  ('home', 'painters', 'rule_4', 'Nothing is finished until you’ve walked it with us and said so.'),
  ('home', 'trade', 'kicker', 'For businesses who manage multiple sites at once'),
  ('home', 'trade', 'h2', 'Every property. One login. No chasing.'),
  ('home', 'trade', 'lead', 'Upload a floorplan, room measurements or photos and get a price range immediately. Approve or request variations at the click of a button, colours kept on file, one click repaint. All invoices in one place. Built for people running twenty jobs, not one.'),
  ('home', 'trade', 'cta_1', 'Book a 15-minute walkthrough'),
  ('home', 'trade', 'cta_2', 'Open a trade account'),
  ('home', 'reviews', 'h2', 'What people say once the tape comes off.'),
  ('home', 'reviews', 'fallback_h2', 'From homeowners and businesses'),
  ('home', 'faq', 'h2', 'Questions people ask before they type their address.'),
  ('home', 'faq', 'q_1', 'What happens after I type my address?'),
  ('home', 'faq', 'a_1', 'You answer a few questions about the property: what''s being painted, roughly how big, the condition. Photos help but aren''t required. A price range appears on screen. Save it and it''s yours to come back to. Nobody rings you unless you ask.'),
  ('home', 'faq', 'q_2', 'Is the price on screen my final price?'),
  ('home', 'faq', 'a_2', 'It''s a real range, and it gets tighter as you answer. The final price is always signed off with you by one of our people. That''s a phone call for apartments, units and smaller jobs, and a site visit for larger ones. Once it''s signed off, that''s the number on your invoice. Anything extra found on site is priced and approved by you first.'),
  ('home', 'faq', 'q_3', 'Who does the painting?'),
  ('home', 'faq', 'a_3', 'Our own trusted network of painters, who are quality-checked, fully insured and used to working in people''s homes and businesses. You''ll see who''s coming in your portal before the start date is locked in.'),
  ('home', 'faq', 'q_4', 'How soon can you start?'),
  ('home', 'faq', 'a_4', 'Once your price is signed off, we''ll give you the earliest start we can hold for a job that size. Smaller interiors are usually quicker than whole-house or exterior work, which depends on the weather. You pick a date that suits from what''s available.'),
  ('home', 'faq', 'q_5', 'Do I need to be home?'),
  ('home', 'faq', 'a_5', 'Not while the painting happens. We''ll agree access with you and send regular photo updates. The final walkthrough is done with you there, so we''ll book it for a time that works.'),
  ('home', 'faq', 'q_6', 'What if you find something extra?'),
  ('home', 'faq', 'a_6', 'It''s raised as a variation with photos and a price. Nothing extra starts, and nothing extra lands on the invoice, until you''ve tapped Approve.'),
  ('home', 'faq', 'q_7', 'When do I pay?'),
  ('home', 'faq', 'a_7', 'A deposit when your price is signed off, and the balance after you''ve walked the job with us and approved it, not before.'),
  ('home', 'faq', 'q_8', 'What does the warranty cover?'),
  ('home', 'faq', 'a_8', 'Our workmanship, for two years from sign-off. If the finish fails because of how it was applied, we come back and fix it. The warranty and our $20M public liability certificate sit in your portal.'),
  ('home', 'cta', 'h2', 'See what it costs to paint your home or business. Now.'),
  ('home', 'cta', 'call_line', 'A real person, Mon to Fri, 8am to 5pm.'),
  ('home', 'meta', 'title_tag', 'Paint Group | See what it costs to paint your home or business'),
  ('home', 'meta', 'meta_description', 'Type your address and see a real painting price range in about ten minutes. Homes and businesses across Melbourne, confirmed by a person before we start.'),
  ('home', 'meta', 'service_type', 'Residential painting'),
  ('business', 'nav', 'link_1_label', 'Commercial jobs'),
  ('business', 'nav', 'link_1_href', '#jobs'),
  ('business', 'nav', 'link_2_label', 'How it works'),
  ('business', 'nav', 'link_2_href', '#how'),
  ('business', 'nav', 'link_3_label', 'For agents & FMs'),
  ('business', 'nav', 'link_3_href', '#trade'),
  ('business', 'nav', 'link_4_label', 'Reviews'),
  ('business', 'nav', 'link_4_href', '#reviews'),
  ('business', 'nav', 'other_audience_label', 'For homes →'),
  ('business', 'nav', 'cta', 'See my price'),
  ('business', 'hero', 'kicker', 'Melbourne · agencies, facilities, strata and businesses · a range today, approvals by link'),
  ('business', 'hero', 'h1', 'Paint your properties
without the chasing.'),
  ('business', 'hero', 'lead', 'Type the address. A vacate, a shopfront, an office, a common area or a whole portfolio. A real price range in about ten minutes, your reference on everything, approvals by link. One invoice run.'),
  ('business', 'hero', 'talk_line', 'Rather talk to a person?'),
  ('business', 'hero', 'chip_home', 'My home'),
  ('business', 'hero', 'chip_business', 'A business or property I manage'),
  ('business', 'hero', 'chips_label', 'This is'),
  ('business', 'hero', 'placeholder', 'Type the property address'),
  ('business', 'hero', 'button', 'See my price →'),
  ('business', 'estimator_examples', 'example_1_address', '4/22 Sydney Road, Coburg'),
  ('business', 'estimator_examples', 'example_1_price', '$3,100 – $3,600'),
  ('business', 'estimator_examples', 'example_1_time', '6 min · vacate paint'),
  ('business', 'estimator_examples', 'example_2_address', 'Level 3, 31 Collins Street, Melbourne CBD'),
  ('business', 'estimator_examples', 'example_2_price', '$1,900 – $2,300'),
  ('business', 'estimator_examples', 'example_2_time', '5 min · touch-up'),
  ('business', 'estimator_examples', 'example_3_address', '118 Glenferrie Road, Malvern'),
  ('business', 'estimator_examples', 'example_3_price', '$6,900 – $7,700'),
  ('business', 'estimator_examples', 'example_3_time', '9 min · shopfront'),
  ('business', 'how_it_works', 'h2', 'Four steps. Your reference on every one.'),
  ('business', 'how_it_works', 'step_1_title', 'Send the job in plain English'),
  ('business', 'how_it_works', 'step_1_body', 'Type the address and tell us what needs painting, or upload a floorplan, measurements or photos. A vacate, a shopfront, an office or a whole floor.'),
  ('business', 'how_it_works', 'step_2_title', 'A range straight back, confirmed by a person'),
  ('business', 'how_it_works', 'step_2_body', 'A real price range appears on screen. One of our people confirms it with you, by phone for smaller jobs and on site for larger ones, before anything is booked.'),
  ('business', 'how_it_works', 'step_3_title', 'Approve by link, PO on every document'),
  ('business', 'how_it_works', 'step_3_body', 'The estimate, every variation and every photo carry your reference. The person you nominate approves by link, and the paper trail sits in your portal.'),
  ('business', 'how_it_works', 'step_4_title', 'One invoice, one login for every property'),
  ('business', 'how_it_works', 'step_4_body', 'Photo updates as the job runs, a walkthrough at the end, then the invoice. Every property you manage sits under one login.'),
  ('business', 'how_it_works', 'talk_line', 'Rather talk to a person first?'),
  ('business', 'jobs', 'kicker', 'Commercial jobs · real prices · inc. GST'),
  ('business', 'jobs', 'h2', 'What Melbourne properties actually cost to paint.'),
  ('business', 'jobs', 'lead', 'Every card is a finished job with the real price. Tap one and we’ll open the estimator pre-filled with the same scope.'),
  ('business', 'jobs', 'all_link', 'All jobs →'),
  ('business', 'promise', 'kicker', 'Our promise · in writing, in your portal'),
  ('business', 'promise', 'h2', 'Four things we put in writing before we start.'),
  ('business', 'promise', 'lead', 'Tap each one to see exactly what it looks like inside your job.'),
  ('business', 'promise', 'panel_kicker', 'What this looks like in your job'),
  ('business', 'promise', 'row_1_title', 'No surprises on the invoice'),
  ('business', 'promise', 'row_1_sub', 'Extra work is priced and approved by your nominated person before it starts.'),
  ('business', 'promise', 'row_1_heading', 'Your painter finds rotten timber behind the fascia. Here''s what happens next.'),
  ('business', 'promise', 'row_1_note', 'Declined variations are recorded on the completion report. Nothing lands on the invoice that your approver didn''t tap Approve on.'),
  ('business', 'promise', 'row_2_title', 'Approvals by link, with a paper trail'),
  ('business', 'promise', 'row_2_sub', 'The estimate and every variation go to the person you nominate. One tap, recorded.'),
  ('business', 'promise', 'row_2_heading', 'The range tightens as you answer. Then the person you nominate approves it by link.'),
  ('business', 'promise', 'row_2_note', 'Every price is confirmed by one of our people before it''s booked. The approval, who gave it and when, sits on the job in your portal.'),
  ('business', 'promise', 'row_3_title', 'Your reference on every photo, report and invoice'),
  ('business', 'promise', 'row_3_sub', 'Give us the PO or job number once. It follows the job everywhere.'),
  ('business', 'promise', 'row_3_heading', 'Every photo, report and invoice carries your reference, so nothing needs matching up later.'),
  ('business', 'promise', 'row_3_note', 'The reference you give us at the start is printed on the estimate, each variation, the completion report and the invoice.'),
  ('business', 'promise', 'row_4_title', '2-year warranty, $20M insured, certificates in the portal'),
  ('business', 'promise', 'row_4_sub', 'Both documents sit in your portal from day one.'),
  ('business', 'promise', 'row_4_heading', 'Both documents are in your portal the day you accept.'),
  ('business', 'promise', 'row_4_note', 'Insurance certificates with their expiry dates and the workmanship warranty sit in your portal for every property, ready to forward.'),
  ('business', 'story', 'kicker', 'Your portal · one job, start to finish · demo data'),
  ('business', 'story', 'h2', 'Watch it happen from wherever you are.'),
  ('business', 'story', 'lead', 'This is what a vacate paint looks like from your desk.'),
  ('business', 'story', 'phone_address', '4/22 High St, Northcote'),
  ('business', 'story', 'phone_meta', 'Vacate paint · PO 4471 · $9,180 inc. GST'),
  ('business', 'story', 'signed_line', 'Signed off · 4/22 High St'),
  ('business', 'story', 'beat_1', 'Monday, 7:31am. Felipe''s on site.'),
  ('business', 'story', 'beat_2', 'You get a message before the first brush touches a wall.'),
  ('business', 'story', 'beat_3', 'Photos from the site.'),
  ('business', 'story', 'beat_4', 'Every area ticked off as it''s finished. No guessing.'),
  ('business', 'story', 'beat_5', 'An update in plain words at the end of each day.'),
  ('business', 'story', 'beat_6', 'Anything extra is priced and approved by your nominated person before it starts.'),
  ('business', 'story', 'beat_7', 'Then a walkthrough with us, room by room.'),
  ('business', 'story', 'beat_8', 'Signed off. Then one invoice.'),
  ('business', 'story', 'beat_9', 'Sent to your PM · PO 4471 on every photo'),
  ('business', 'live', 'heading', 'Live from the Paint Group platform'),
  ('business', 'painters', 'h2', 'Who’ll be painting.'),
  ('business', 'painters', 'lead', 'The same trusted network of painters our homeowners get. Every one is quality-checked, fully insured, and used to working on tenanted, occupied and after-hours sites. You’ll know who’s coming before the date is locked in.'),
  ('business', 'painters', 'rule_1', 'Your expectations are documented for your painter before day one. No nasty surprises, for you or for them.'),
  ('business', 'painters', 'rule_2', 'The finish you’re paying for is written on the work order, room by room.'),
  ('business', 'painters', 'rule_3', 'Photos from the site, so you never have to wonder how it’s going.'),
  ('business', 'painters', 'rule_4', 'Nothing is finished until it has been walked and signed off.'),
  ('business', 'trade', 'kicker', 'For agents, facilities managers, strata and owners of more than one site'),
  ('business', 'trade', 'h2', 'Every property. One login. No chasing.'),
  ('business', 'trade', 'lead', 'Upload a floorplan, room measurements or photos and get a price range immediately. Approve or request variations at the click of a button, colours kept on file, one click repaint. All invoices in one place. Built for people running twenty jobs, not one.'),
  ('business', 'trade', 'cta_1', 'Book a 15-minute walkthrough'),
  ('business', 'trade', 'cta_2', 'Open a trade account'),
  ('business', 'reviews', 'h2', 'What businesses say once the tape comes off.'),
  ('business', 'reviews', 'fallback_h2', 'From homeowners and businesses'),
  ('business', 'faq', 'h2', 'Questions agents and facilities managers ask first.'),
  ('business', 'faq', 'q_1', 'Can you work after hours or weekends?'),
  ('business', 'faq', 'a_1', '[Tom to confirm] Tell us the access window when you send the job and we price to it.'),
  ('business', 'faq', 'q_2', 'Do you handle multiple sites under one account?'),
  ('business', 'faq', 'a_2', 'Yes. A trade account holds every property you manage under one login: each job, its photos, approvals and invoices, and the colours on file for a one-click repaint.'),
  ('business', 'faq', 'q_3', 'Can you put our PO number on everything?'),
  ('business', 'faq', 'a_3', 'Yes. Give us the PO or job number once and it is printed on the estimate, every variation, every photo report and the invoice.'),
  ('business', 'faq', 'q_4', 'How fast can you turn a vacate paint around?'),
  ('business', 'faq', 'a_4', '[Tom to confirm] A vacate paint is usually the quickest job we do. Send the address and the handover date and we will tell you the earliest start we can hold.'),
  ('business', 'faq', 'q_5', 'Who approves variations on our side?'),
  ('business', 'faq', 'a_5', 'Whoever you nominate. Anything extra found on site is raised as a variation with photos and a price, and it goes to your approver by link. Nothing extra starts, and nothing extra lands on the invoice, until they tap Approve. The approval is recorded on the job.'),
  ('business', 'faq', 'q_6', 'Can we get one invoice for the month?'),
  ('business', 'faq', 'a_6', '[Tom to confirm] Every invoice sits in your portal under the property it belongs to, with your reference on it.'),
  ('business', 'faq', 'q_7', 'Are you insured for commercial sites and do you provide certificates?'),
  ('business', 'faq', 'a_7', 'Yes. We carry $20M public liability, and the certificates with their expiry dates sit in your portal alongside our two-year workmanship warranty, ready to forward to whoever needs them.'),
  ('business', 'faq', 'q_8', 'Do you do body-corporate and strata common areas?'),
  ('business', 'faq', 'a_8', 'Yes. Common areas, stairwells, car parks and external walls of apartment buildings. [Tom to confirm] the sign-off process for committee approvals.'),
  ('business', 'cta', 'h2', 'See what it costs to paint your property. Now.'),
  ('business', 'cta', 'call_line', 'A real person, Mon to Fri, 8am to 5pm.'),
  ('business', 'meta', 'title_tag', 'Commercial painters Melbourne | see your price today | Paint Group'),
  ('business', 'meta', 'meta_description', 'Type the property address and see a real painting price range in about ten minutes. Vacates, shopfronts, offices, common areas and whole portfolios across Melbourne, your reference on everything, approvals by link.'),
  ('business', 'meta', 'service_type', 'Commercial painting')
on conflict (tenant_id, audience, section, key, sort) do nothing;

-- ---- read-back ------------------------------------------------------------------
do $$
begin
  if (select count(*) from pg_policies where schemaname = 'public' and tablename = 'site_content') <> 1 then
    raise exception 'read-back: expected 1 policy on site_content';
  end if;
  if (select count(*) from pg_policies where schemaname = 'public' and tablename = 'review_tags') <> 1 then
    raise exception 'read-back: expected 1 policy on review_tags';
  end if;
  if exists (select 1 from information_schema.role_table_grants where table_schema = 'public' and table_name in ('site_content', 'review_tags')
             and grantee in ('anon', 'authenticated') and privilege_type in ('INSERT', 'UPDATE', 'DELETE')) then
    raise exception 'read-back: a client role still holds a write grant';
  end if;
  if (select count(*) from public.site_content where audience = 'business') < 100 then
    raise exception 'read-back: business seed missing';
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'showcase_jobs' and column_name = 'featured_rank_business') then
    raise exception 'read-back: featured_rank_business missing';
  end if;
end $$;

-- Paste the result in chat: expect two rows, home and business, each with 100+ keys.
select audience, count(*) as keys from public.site_content group by audience order by audience;
