import type { SiteCopy } from "./schema";

/**
 * The commercial site's copy — the brief's §6 draft, worked through by Tom
 * in Settings → Website after the build (ruling: ship it in the editor, not
 * in code). FAQ answers come from what the platform actually does; where
 * that is policy Tom has not ruled, the answer is a visible
 * "[Tom to confirm]" placeholder rather than an invented promise (⚑ D5).
 * No em dashes anywhere (Tom, 5 Sep).
 */
export const BUSINESS_COPY: SiteCopy = {
  nav: {
    link_1_label: "Commercial jobs", link_1_href: "#jobs",
    link_2_label: "How it works", link_2_href: "#how",
    link_3_label: "For agents & FMs", link_3_href: "#trade",
    link_4_label: "Reviews", link_4_href: "#reviews",
    other_audience_label: "For homes →",
    cta: "See my price",
  },
  hero: {
    kicker: "Melbourne · agencies, facilities, strata and businesses · a range today, approvals by link",
    h1: "Paint your properties\nwithout the chasing.",
    lead: "Type the address. A vacate, a shopfront, an office, a common area or a whole portfolio. A real price range in about ten minutes, your reference on everything, approvals by link. One invoice run.",
    talk_line: "Rather talk to a person?",
    chip_home: "My home", chip_business: "A business or property I manage", chips_label: "This is",
    placeholder: "Type the property address", button: "See my price →",
  },
  estimator_examples: {
    example_1_address: "4/22 Sydney Road, Coburg", example_1_price: "$3,100 – $3,600", example_1_time: "6 min · vacate paint",
    example_2_address: "Level 3, 31 Collins Street, Melbourne CBD", example_2_price: "$1,900 – $2,300", example_2_time: "5 min · touch-up",
    example_3_address: "118 Glenferrie Road, Malvern", example_3_price: "$6,900 – $7,700", example_3_time: "9 min · shopfront",
  },
  how_it_works: {
    h2: "Four steps. Your reference on every one.",
    step_1_title: "Send the job in plain English",
    step_1_body: "Type the address and tell us what needs painting, or upload a floorplan, measurements or photos. A vacate, a shopfront, an office or a whole floor.",
    step_2_title: "A range straight back, confirmed by a person",
    step_2_body: "A real price range appears on screen. One of our people confirms it with you, by phone for smaller jobs and on site for larger ones, before anything is booked.",
    step_3_title: "Approve by link, PO on every document",
    step_3_body: "The estimate, every variation and every photo carry your reference. The person you nominate approves by link, and the paper trail sits in your portal.",
    step_4_title: "One invoice, one login for every property",
    step_4_body: "Photo updates as the job runs, a walkthrough at the end, then the invoice. Every property you manage sits under one login.",
    talk_line: "Rather talk to a person first?",
  },
  jobs: {
    kicker: "Commercial jobs · real prices · inc. GST",
    h2: "What Melbourne properties actually cost to paint.",
    lead: "Every card is a finished job with the real price. Tap one and we’ll open the estimator pre-filled with the same scope.",
    all_link: "All jobs →",
  },
  promise: {
    kicker: "Our promise · in writing, in your portal",
    h2: "Four things we put in writing before we start.",
    lead: "Tap each one to see exactly what it looks like inside your job.",
    panel_kicker: "What this looks like in your job",
    row_1_title: "No surprises on the invoice",
    row_1_sub: "Extra work is priced and approved by your nominated person before it starts.",
    row_1_heading: "Your painter finds rotten timber behind the fascia. Here's what happens next.",
    row_1_note: "Declined variations are recorded on the completion report. Nothing lands on the invoice that your approver didn't tap Approve on.",
    row_2_title: "Approvals by link, with a paper trail",
    row_2_sub: "The estimate and every variation go to the person you nominate. One tap, recorded.",
    row_2_heading: "The range tightens as you answer. Then the person you nominate approves it by link.",
    row_2_note: "Every price is confirmed by one of our people before it's booked. The approval, who gave it and when, sits on the job in your portal.",
    row_3_title: "Your reference on every photo, report and invoice",
    row_3_sub: "Give us the PO or job number once. It follows the job everywhere.",
    row_3_heading: "Every photo, report and invoice carries your reference, so nothing needs matching up later.",
    row_3_note: "The reference you give us at the start is printed on the estimate, each variation, the completion report and the invoice.",
    row_4_title: "2-year warranty, $20M insured, certificates in the portal",
    row_4_sub: "Both documents sit in your portal from day one.",
    row_4_heading: "Both documents are in your portal the day you accept.",
    row_4_note: "Insurance certificates with their expiry dates and the workmanship warranty sit in your portal for every property, ready to forward.",
  },
  story: {
    kicker: "Your portal · one job, start to finish · demo data",
    h2: "Watch it happen from wherever you are.",
    lead: "This is what a vacate paint looks like from your desk.",
    phone_address: "4/22 High St, Northcote",
    phone_meta: "Vacate paint · PO 4471 · $9,180 inc. GST",
    signed_line: "Signed off · 4/22 High St",
    beat_1: "Monday, 7:31am. Felipe's on site.",
    beat_2: "You get a message before the first brush touches a wall.",
    beat_3: "Photos from the site.",
    beat_4: "Every area ticked off as it's finished. No guessing.",
    beat_5: "An update in plain words at the end of each day.",
    beat_6: "Anything extra is priced and approved by your nominated person before it starts.",
    beat_7: "Then a walkthrough with us, room by room.",
    beat_8: "Signed off. Then one invoice.",
    beat_9: "Sent to your PM · PO 4471 on every photo",
  },
  live: { heading: "Live from the Paint Group platform" },
  painters: {
    h2: "Who’ll be painting.",
    lead: "The same trusted network of painters our homeowners get. Every one is quality-checked, fully insured, and used to working on tenanted, occupied and after-hours sites. You’ll know who’s coming before the date is locked in.",
    rule_1: "Your expectations are documented for your painter before day one. No nasty surprises, for you or for them.",
    rule_2: "The finish you’re paying for is written on the work order, room by room.",
    rule_3: "Photos from the site, so you never have to wonder how it’s going.",
    rule_4: "Nothing is finished until it has been walked and signed off.",
  },
  trade: {
    kicker: "For agents, facilities managers, strata and owners of more than one site",
    h2: "Every property. One login. No chasing.",
    lead: "Upload a floorplan, room measurements or photos and get a price range immediately. Approve or request variations at the click of a button, colours kept on file, one click repaint. All invoices in one place. Built for people running twenty jobs, not one.",
    cta_1: "Book a 15-minute walkthrough",
    cta_2: "Open a trade account",
  },
  reviews: {
    h2: "What businesses say once the tape comes off.",
    fallback_h2: "From homeowners and businesses",
  },
  faq: {
    h2: "Questions agents and facilities managers ask first.",
    q_1: "Can you work after hours or weekends?",
    a_1: "[Tom to confirm] Tell us the access window when you send the job and we price to it.",
    q_2: "Do you handle multiple sites under one account?",
    a_2: "Yes. A trade account holds every property you manage under one login: each job, its photos, approvals and invoices, and the colours on file for a one-click repaint.",
    q_3: "Can you put our PO number on everything?",
    a_3: "Yes. Give us the PO or job number once and it is printed on the estimate, every variation, every photo report and the invoice.",
    q_4: "How fast can you turn a vacate paint around?",
    a_4: "[Tom to confirm] A vacate paint is usually the quickest job we do. Send the address and the handover date and we will tell you the earliest start we can hold.",
    q_5: "Who approves variations on our side?",
    a_5: "Whoever you nominate. Anything extra found on site is raised as a variation with photos and a price, and it goes to your approver by link. Nothing extra starts, and nothing extra lands on the invoice, until they tap Approve. The approval is recorded on the job.",
    q_6: "Can we get one invoice for the month?",
    a_6: "[Tom to confirm] Every invoice sits in your portal under the property it belongs to, with your reference on it.",
    q_7: "Are you insured for commercial sites and do you provide certificates?",
    a_7: "Yes. We carry $20M public liability, and the certificates with their expiry dates sit in your portal alongside our two-year workmanship warranty, ready to forward to whoever needs them.",
    q_8: "Do you do body-corporate and strata common areas?",
    a_8: "Yes. Common areas, stairwells, car parks and external walls of apartment buildings. [Tom to confirm] the sign-off process for committee approvals.",
  },
  cta: {
    h2: "See what it costs to paint your property. Now.",
    call_line: "A real person, Mon to Fri, 8am to 5pm.",
  },
  meta: {
    title_tag: "Commercial painters Melbourne | see your price today | Paint Group",
    meta_description: "Type the property address and see a real painting price range in about ten minutes. Vacates, shopfronts, offices, common areas and whole portfolios across Melbourne, your reference on everything, approvals by link.",
    service_type: "Commercial painting",
  },
};
