import type { SiteCopy } from "./schema";

/**
 * The residential homepage's copy, extracted verbatim from the sections as
 * built (session 8 §3: "no copy stays hard-coded after this session"). The
 * seed migration is generated from this object (scripts/gen-site-content-seed.ts)
 * and it is also the runtime fallback when a row is missing, so a fresh
 * environment renders the same page before the migration runs.
 */
export const HOME_COPY: SiteCopy = {
  nav: {
    link_1_label: "Real jobs, real prices", link_1_href: "/work",
    link_2_label: "How it works", link_2_href: "#how",
    link_3_label: "For business", link_3_href: "#trade",
    link_4_label: "Reviews", link_4_href: "#reviews",
    other_audience_label: "For business →",
    cta: "See my price",
  },
  hero: {
    kicker: "Melbourne · homes and businesses · see your price today · confirmed by a person before we start",
    h1: "Transforming spaces.\nRedefining painting.",
    lead: "Type the address. A home, a shop, an office or a whole portfolio. See a real price range in about ten minutes.",
    talk_line: "Rather talk to a person?",
    chip_home: "My home", chip_business: "A business or property I manage", chips_label: "This is",
    placeholder: "Type your address", button: "See my price →",
  },
  estimator_examples: {
    example_1_address: "12 Elm Street, Malvern", example_1_price: "$8,400 – $9,600", example_1_time: "9 min to a range",
    example_2_address: "9 Clarke Street, Beaumaris", example_2_price: "$14,200 – $15,800", example_2_time: "11 min · exterior",
    example_3_address: "27 Wattle Avenue, Coburg", example_3_price: "$5,300 – $6,100", example_3_time: "8 min · 3 rooms",
  },
  how_it_works: {
    h2: "Four steps. You’re in charge of every one.",
    step_1_title: "See your price",
    step_1_body: "Type your address, answer a few questions, add photos if you have them. A price range appears on screen. About ten minutes.",
    step_2_title: "We confirm it with you",
    step_2_body: "The more you tell us, the tighter the range. Our estimator will go through all of the details with you in person, or over the phone to confirm your price.",
    step_3_title: "Pick your dates",
    step_3_body: "Once the price is signed off, choose a start that suits you. We confirm your painter before we lock it in. You’ll know who’s coming.",
    step_4_title: "Sign off, then pay",
    step_4_body: "Photo updates in your portal. A walkthrough with you at the end. You sign off, then the final invoice is due.",
    talk_line: "Rather talk to a person first?",
  },
  jobs: {
    kicker: "Real jobs · real prices · inc. GST",
    h2: "What Melbourne properties actually cost to paint.",
    lead: "Every card is a finished job with the real price. Tap one and we’ll open the estimator pre-filled with the same scope.",
    all_link: "All jobs →",
  },
  promise: {
    kicker: "Our promise · in writing, in your portal",
    h2: "Four things we put in writing before we start.",
    lead: "Tap each one to see exactly what it looks like inside your job.",
    panel_kicker: "What this looks like in your job",
    row_1_title: "No surprises on the invoice",
    row_1_sub: "Extra work is priced and approved by you before it starts.",
    row_1_heading: "Your painter finds rotten timber behind the fascia. Here's what happens next.",
    row_1_note: "Declined variations are recorded on your completion report. Nothing lands on the invoice that you didn't tap Approve on.",
    row_2_title: "A price a person signs off with you",
    row_2_sub: "Your range tightens as you go, then we confirm it together before anything is booked.",
    row_2_heading: "Your range gets tighter with every answer. Then we sign it off together.",
    row_2_note: "Every price is signed off by one of our people before it's booked: a call for apartments, units and smaller jobs, a visit for larger or older homes. What we sign off together is what goes on the invoice.",
    row_3_title: "You sign off before you pay",
    row_3_sub: "The final invoice waits for your walkthrough.",
    row_3_heading: "The last day on site is a walkthrough with you, area by area.",
    row_3_note: "The walkthrough is done with you, on site. Flagged items are fixed first; the invoice follows your signature.",
    row_4_title: "2-year warranty, $20M insured",
    row_4_sub: "Both documents sit in your portal from day one.",
    row_4_heading: "Both documents are in your portal the day you accept.",
    row_4_note: "Six months from now you'll want to know which white is on the hallway. It's here.",
  },
  story: {
    kicker: "Your portal · one job, start to finish · demo data",
    h2: "Watch it happen from wherever you are.",
    lead: "This is what five days looks like from your phone.",
    phone_address: "12 Elm Street, Northcote",
    phone_meta: "Interior · 4 rooms + hallway · $9,180 inc. GST",
    signed_line: "Signed off · 12 Elm Street",
    beat_1: "Monday, 7:31am. Felipe's on site.",
    beat_2: "You get a message before the first brush touches a wall.",
    beat_3: "Photos from the site.",
    beat_4: "Every area ticked off as it's finished. No guessing.",
    beat_5: "An update in plain words at the end of each day.",
    beat_6: "Anything extra is priced and approved by you before it starts.",
    beat_7: "Then you walk it with us, room by room.",
    beat_8: "You sign off. Then you pay.",
    beat_9: "",
  },
  live: { heading: "Live from the Paint Group platform" },
  painters: {
    h2: "Who’ll be painting.",
    lead: "Our trusted network of painters. Every one is quality-checked, fully insured, and the kind of person you’ll be comfortable having in your home or on your premises. You’ll know who’s coming before the date is locked in.",
    rule_1: "Your expectations are documented for your painter before day one. No nasty surprises, for you or for them.",
    rule_2: "The finish you’re paying for is written on the work order, room by room.",
    rule_3: "Photos from the site, so you never have to wonder how it’s going.",
    rule_4: "Nothing is finished until you’ve walked it with us and said so.",
  },
  trade: {
    kicker: "For businesses who manage multiple sites at once",
    h2: "Every property. One login. No chasing.",
    lead: "Upload a floorplan, room measurements or photos and get a price range immediately. Approve or request variations at the click of a button, colours kept on file, one click repaint. All invoices in one place. Built for people running twenty jobs, not one.",
    cta_1: "Book a 15-minute walkthrough",
    cta_2: "Open a trade account",
  },
  reviews: {
    h2: "What people say once the tape comes off.",
    fallback_h2: "From homeowners and businesses",
  },
  faq: {
    h2: "Questions people ask before they type their address.",
    q_1: "What happens after I type my address?",
    a_1: "You answer a few questions about the property: what's being painted, roughly how big, the condition. Photos help but aren't required. A price range appears on screen. Save it and it's yours to come back to. Nobody rings you unless you ask.",
    q_2: "Is the price on screen my final price?",
    a_2: "It's a real range, and it gets tighter as you answer. The final price is always signed off with you by one of our people. That's a phone call for apartments, units and smaller jobs, and a site visit for larger ones. Once it's signed off, that's the number on your invoice. Anything extra found on site is priced and approved by you first.",
    q_3: "Who does the painting?",
    a_3: "Our own trusted network of painters, who are quality-checked, fully insured and used to working in people's homes and businesses. You'll see who's coming in your portal before the start date is locked in.",
    q_4: "How soon can you start?",
    a_4: "Once your price is signed off, we'll give you the earliest start we can hold for a job that size. Smaller interiors are usually quicker than whole-house or exterior work, which depends on the weather. You pick a date that suits from what's available.",
    q_5: "Do I need to be home?",
    a_5: "Not while the painting happens. We'll agree access with you and send regular photo updates. The final walkthrough is done with you there, so we'll book it for a time that works.",
    q_6: "What if you find something extra?",
    a_6: "It's raised as a variation with photos and a price. Nothing extra starts, and nothing extra lands on the invoice, until you've tapped Approve.",
    q_7: "When do I pay?",
    a_7: "A deposit when your price is signed off, and the balance after you've walked the job with us and approved it, not before.",
    q_8: "What does the warranty cover?",
    a_8: "Our workmanship, for two years from sign-off. If the finish fails because of how it was applied, we come back and fix it. The warranty and our $20M public liability certificate sit in your portal.",
  },
  cta: {
    h2: "See what it costs to paint your home or business. Now.",
    call_line: "A real person, Mon to Fri, 8am to 5pm.",
  },
  meta: {
    title_tag: "Paint Group | See what it costs to paint your home or business",
    meta_description: "Type your address and see a real painting price range in about ten minutes. Homes and businesses across Melbourne, confirmed by a person before we start.",
    service_type: "Residential painting",
  },
};
